services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: web
    ports:
      - "5000:5000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      WEB_URL: http://web:5000/predict
    depends_on:
      - web
